language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
  - coveralls
