pipeline:
  prepare:
    image: python:3.11-alpine
    commands:
      - python3 -m venv .venv

  install-dependencies:
    image: python:3.11-alpine
    commands:
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  test:
    image: python:3.11-alpine
    commands:
      - . .venv/bin/activate
      - apk update && apk add make
      - make test

  coverage:
    image: python:3.11-alpine
    commands:
      - . .venv/bin/activate
      - apk update && apk add make
      - make coverage
