version: 1
jobs:
  build:
    working_directory: ~/flask-ci-test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          command: |
            pytest