version: 3
jobs:
  build:
    working_directory: ~/flask-ci-test
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: pip install -r requirements.txt
  test:
    working_directory: ~/flask-ci-test
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: pip install -r requirements.txt
      - run:
          name: Running tests with tox
          command: tox
      - run:
          name: Uploading test report
          command: codecov && python-codacy-coverage -r coverage.xml && coveralls
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
